### ISSUE TITLE
Deploy to Digital Ocean - Couldn't find environment variable: S3_PATH_PREFIX

### ISSUE THREAD

**Issue by djmkee** [hashlips-lab/safe-nft-metadata-provider#59]
I am getting this regardless what i try

[pepe-metadata] [2023-04-02 19:39:35] yarn run v1.22.19
[pepe-metadata] [2023-04-02 19:39:35] $ node dist/index.js
[pepe-metadata] [2023-04-02 19:39:36] /workspace/dist/config.js:13
[pepe-metadata] [2023-04-02 19:39:36]         throw new Error(`Couldn't find environment variable: ${environmentVariable}`);
[pepe-metadata] [2023-04-02 19:39:36]         ^
[pepe-metadata] [2023-04-02 19:39:36] 
[pepe-metadata] [2023-04-02 19:39:36] Error: Couldn't find environment variable: S3_PATH_PREFIX
[pepe-metadata] [2023-04-02 19:39:36]     at getEnvironmentVariable (/workspace/dist/config.js:13:15)
[pepe-metadata] [2023-04-02 19:39:36]     at Object.<anonymous> (/workspace/dist/config.js:24:21)
[pepe-metadata] [2023-04-02 19:39:36]     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[pepe-metadata] [2023-04-02 19:39:36]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[pepe-metadata] [2023-04-02 19:39:36]     at Module.load (node:internal/modules/cjs/loader:1074:32)
[pepe-metadata] [2023-04-02 19:39:36]     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[pepe-metadata] [2023-04-02 19:39:36]     at Module.require (node:internal/modules/cjs/loader:1098:19)
[pepe-metadata] [2023-04-02 19:39:36]     at require (node:internal/modules/cjs/helpers:108:18)
[pepe-metadata] [2023-04-02 19:39:36]     at Object.<anonymous> (/workspace/dist/index.js:4:18)
[pepe-metadata] [2023-04-02 19:39:36]     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[pepe-metadata] [2023-04-02 19:39:36] error Command failed with exit code 1.
[pepe-metadata] [2023-04-02 19:39:36] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by djmkee** [comment]
issue between chair and keyboard
